core/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import (Home, Checkout, ProductDetail, 
                add_to_cart, remove_from_cart, 
                OrderSummary, remove_single_item_from_cart,
                PayPalPayment, payment_done, payment_canceled, 
                Search, AddCoupon, StripePayment, RefundRequest,
                UserProfileView, AddLenses, RemoveLenses)
                
app_name = "core"
handler404 = 'core.views.page_not_found_view'

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("order-summary/", OrderSummary.as_view(), name="order-summary"),
    path("checkout/", Checkout.as_view(), name="checkout"),
    path("product/<slug>", ProductDetail.as_view(), name="product-detail"),
    path("add-to-cart/<slug>", add_to_cart, name="add_to_cart"),
    path("add-coupon/", AddCoupon.as_view(), name="add_coupon"),
    path("add-lenses/<slug>", AddLenses.as_view(), name="add_lenses"),
    path("remove-lenses/<slug>", RemoveLenses.as_view(), name="remove_lenses"),
    path("remove-from-cart/<slug>", remove_from_cart, name="remove_from_cart"),
    path("remove-single-item-from-cart/<slug>", remove_single_item_from_cart, name="remove_single_item_from_cart"),
    path('paypal-payment/', PayPalPayment.as_view(), name='paypal_payment'),
    path('stripe-payment/', StripePayment.as_view(), name='stripe_payment'),
    path('payment-done/', payment_done, name='payment_done'),
    path('payment-cancelled/', payment_canceled, name='payment_cancelled'),
    path('search/',Search.as_view(), name='search'),
    path("refund-request/", RefundRequest.as_view(), name="refund_request"),
    path("user/", UserProfileView.as_view(), name="user_profile"),


    # REST API URL
    path('api/', include('core.api.urls', namespace="api")),
]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace="core")),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.core.exceptions import ObjectDoesNotExist
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

CATEGORIES_CHOICES = (
    ('FS', "Full Sheet Frame"),
    ('FM', "Full Metal Frame"),
    ('3P', "Without Frame"),
    ('SP', "Half Frame"),
)

POWER_TYPES_CHOICES = (
    ('Z', "Zero Power"),
    ('B', "Bifocal Power"),
    ('S', "Single Power"),
)

LENSES_TYPES_CHOICES = (
    ('HC', "Regular"),
    ('AR', "Anti-Glare"),
    ('BB', "Blue Blocker"),
)

LABEL_CHOICES = (
    ('P', "primary"),
    ('S', "secondary"),
    ('D', "danger"),
)


ADDRESS_CHOICES = (
    ('B', "Billing"),
    ('S', "Shipping"),
)


# Create your models here.
class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(max_length=2, choices=CATEGORIES_CHOICES)
    label = models.CharField(max_length=1, choices=LABEL_CHOICES)
    slug = models.SlugField()
    description = models.TextField(default="This is a description of the product.")
    features = models.TextField(default="This is a description of the product.")
    fview = models.ImageField(upload_to="media/Item/", blank=True, null=True)
    sview = models.ImageField(upload_to="media/Item/", blank=True, null=True)

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse("core:product-detail", kwargs={
            "slug":self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add_to_cart", kwargs={
            "slug":self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove_from_cart", kwargs={
            "slug":self.slug
        })

class OrderItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    lenses_required = models.BooleanField(default=False)
    lenses = models.ForeignKey('EyeLenses', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price
        
    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price
        
    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        else:
            return self.get_total_item_price()        

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    order_date = models.DateTimeField()
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL, null=True, blank=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, null=True, blank=True)

    failed_confirm = models.BooleanField(default=False)
    remark_for_failure = models.TextField(default="Please Contact to the store.")
    in_process_delivery = models.BooleanField(default=False)

    delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)

    refund_request = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return str(self.user.username)

    def get_total_bill_amount(self):
        total_amount = 0
        for item in self.items.all():
            total_amount += item.get_final_price()
        return total_amount
        
    def get_total_bill_amount_with_discount(self):
        total_amount = 0
        for item in self.items.all():
            total_amount += item.get_final_price()
        if self.coupon:
            total_amount -= total_amount * (self.coupon.percentage/100)
        return total_amount

class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip_code = models.CharField(max_length=10)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)
    

    class Meta:
        verbose_name_plural = 'Addresses'

    def __str__(self):
        return self.user.username

class Payment(models.Model):
    transaction_id = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    time_stamp = models.DateTimeField(auto_now_add=True)
    amount = models.FloatField()
    def __str__(self):
        return f"$ {self.amount} bill of {self.user.username}"

class Coupon(models.Model):
    code = models.CharField(max_length=50)
    percentage = models.FloatField(default=0)
    def __str__(self):
        return self.code

class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    email = models.EmailField()
    message = models.TextField()
    accepted = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.pk}"

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    profile_image = models.ImageField(blank=True, null=True)
    phone = models.CharField(max_length=10,blank=True, null=True)

    def __str__(self):
        return self.user.username

class EyeLenses(models.Model):
    power_type = models.CharField(blank=True, null=True, max_length=1, choices=POWER_TYPES_CHOICES)
    lenses_type = models.CharField(blank=True, null=True, max_length=2, choices=LENSES_TYPES_CHOICES)
    prescription_image = models.ImageField(upload_to = "user_prescription/", blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

core/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

PAYMENT_CHOICE =(
    ('S','Stripe'),
    ('P','PayPal'),
)

POWER_TYPES_CHOICES = (
    ('Z', "Zero Power"),
    ('B', "Bifocal Power"),
    ('S', "Single Power"),
)

LENSES_TYPES_CHOICES = (
    ('HC', "Regular"),
    ('AR', "Anti-Glare"),
    ('BB', "Blue Blocker"),
)
class CheckoutForm(forms.Form):
    shipping_street_address = forms.CharField(required=False)
    shipping_apartment_address = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(Select Country)').formfield(
        required=False,
        widget=CountrySelectWidget(
           attrs={"class": "custom-select d-block w-100"}
        )
    )
    shipping_zip_code = forms.CharField(required=False)
    save_info = forms.BooleanField(widget=forms.CheckboxInput(),required=False)
    use_default_shipping = forms.BooleanField(widget=forms.CheckboxInput(),required=False)
    set_default_shipping = forms.BooleanField(widget=forms.CheckboxInput(),required=False)
    payment_method = forms.ChoiceField(widget=forms.RadioSelect(), choices=PAYMENT_CHOICE)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class':"form-control",
        'placeholder':'Promo Code',
        'aria-label':"Recipient's username",
        'aria-describedby':"basic-addon2"
    }))

class LensesForm(forms.Form):
    power_type = forms.ChoiceField(widget=forms.Select(
        attrs={
            "class": "custom-select d-block w-100",
            "id": "power_type",
        }
    ), choices=POWER_TYPES_CHOICES)

    lenses_type = forms.ChoiceField(widget=forms.Select(
        attrs={
            "class": "custom-select d-block w-100",
            "id": "lenses_type",
        }), choices=LENSES_TYPES_CHOICES)


    prescription_image = forms.ImageField()

class StripePaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)


class RefundForm(forms.Form):
    email = forms.EmailField(required=True)
    message = forms.CharField(required=True, widget = forms.Textarea(
        attrs={
            'rows': 4,
        }
    ))
    ref_code = forms.CharField(required=True)

templates/lenses_requirements.html
{% extends "base.html" %}
{% load cart_template_tags %}

{% load staticfiles %}

{% block head_title  %}Lenses Requirement{% endblock %}
{% block content %}


  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-4 mb-4">
          <img src="{{ product.item.fview.url }}" class="mw-100" alt="{{product.item.slug}}">
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{product.item.get_category_display}}</span>
              </a>
            </div>

            <p class="lead">

              {% if product.item.discount_price %}
                <span class="mr-1">
                  <del>₹{{product.item.price}}</del>
                </span>
                <span>₹{{product.item.discount_price}}</span>
              {% else %}
                      {{product.item.price}}
              {% endif %}
              
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{product.item.features|safe}}
                {% if product.lenses_required %}
                    ✔ <b>{{product.lenses.get_power_type_display}} - {{product.lenses.get_lenses_type_display}}</b><!-- Button trigger modal -->
                        <a class="btn btn-primary btn-sm" href="{% url "core:remove_lenses" slug=product.item.slug %}">
                          Remove Lenses
                        </a>
                {% else %}
                    ✖ Don't Require Lenses   <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#LensesForm">
                        Changed mind?
                        </button>
                {% endif %}
            </p>
              <a class="btn btn-primary btn-md my-0 p" href="{{product.item.get_add_to_cart_url}}">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>
              
              <a class="btn btn-danger btn-md my-0 p" href="{{product.item.get_remove_from_cart_url}}">Remove from cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

    </div>
  </main>
  <!--Main layout-->



<!-- Form for Lenses Information -->
<div class="modal fade" id="LensesForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
            <h4 class="modal-title w-100 font-weight-bold">Lenses Information</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="modal-body mx-3">
                  <div class="md-form mb-5">
                  <label for="power_type" style="position: relative; margin-bottom: 1em;">Power Type</label>
                  {% comment %} <input type="text" id="orangeForm-name" class="form-control validate"> {% endcomment %}
                  {{ form.power_type }}
                  </div>
                  <div class="md-form mb-5">
                  <label for="lenses_type" style="position: relative; margin-bottom: 1em;">Lenses Type</label>
                  {{ form.lenses_type }}
                  </div>

                  <div class="md-form mb-4">
                  <label for="prescription_image" style="position: relative; margin-bottom: 1em;" id="id_prescription_image">Prescription Image</label>
                  {{ form.prescription_image }}
                  </div>

              </div>
              <div class="modal-footer d-flex justify-content-center">
                  <input type="submit" class="btn btn-deep-orange">
              </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

{% block extra_script %}
<script>
  var hideable_lenses_form = $('#LensesForm');

  var lenses_required = document.querySelector("input[name=lenses_required]");

  lenses_required.addEventListener('change', function (){
    if(this.checked){
      $('#LensesForm').modal('show')
    }
    else{
      $('#LensesForm').modal('hide')
    }
  });
</script>
{% endblock %}

templates/navbar.html
{% load staticfiles %}
{% load cart_template_tags %}

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'core:home' %}">
        <strong class="blue-text">ECom</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %}
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url 'core:home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'core:checkout' %}">Check Out</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'core:product-detail' %}">Product</a>
          </li> {% endcomment %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
                <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                <i class="fas fa-shopping-cart"></i>
                <span class="clearfix d-none d-sm-inline-block"> Cart </span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'core:user_profile' %}"><i class="fas fa-user"></i></a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'account_logout' %}"><i class="fas fa-sign-out-alt"></i></a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'account_login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'account_signup' %}">Sign Up</a>
            </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

templates/order_snippet.html
<!--Grid column-->
<div class="col-md-12 mb-4">

    <!-- Heading -->
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ cart.items.count }}</span>
    </h4>

    <!-- Cart -->
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in cart.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
            <h6 class="my-0">{{ order_item.item.title }}</h6>
            <small class="text-muted">
            {% if order_item.item.discount_price %}
                    {{order_item.item.discount_price}} x {{order_item.quantity}}
            {% else %}
                {{order_item.item.price}} x {{order_item.quantity}}
            {% endif %}
            </small>
        </div>
        <span class="text-muted">
            
            {% if order_item.get_total_discount_item_price %}
            ₹{{ order_item.get_total_discount_item_price }}
            {% else %}
            ₹{{ order_item.get_total_item_price }}
            {% endif %}

        </span>
        </li>
        {% endfor %}
        {% if cart.coupon %}
        <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>{{cart.coupon.code}}</small>
        </div>
        <span class="text-success">-{{cart.coupon.percentage}}%</span>
        </li>
         {% endif %}
        <li class="list-group-item d-flex justify-content-between">
        <span>Total (INR)</span>
        <strong>₹{{cart.get_total_bill_amount_with_discount}}</strong>
        </li>
    </ul>
    <!-- Cart -->
   
    {% if DISPLAY_COUPON_FORM %}
    <!-- Promo code -->
    <form class="card p-2" method="POST" action="{% url 'core:add_coupon' %}">
        {% csrf_token %}
        <div class="input-group">
        {{ couponform.code }}
        <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
        </div>
        </div>
    </form>
    <!-- Promo code -->
    {% endif %}
    
</div>
<!--Grid column-->
<!--Card-->
<div class="center">
    {{ form.render }}
</div>
<!--/.Card-->

templates/order_summary.html
{% extends "base.html" %}

{% load staticfiles %}

{% block extra_head  %}
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
{% endblock %}
{% block title  %}Home{% endblock %}



{% block content %}

  <!--Main layout-->
  <main>
    <div class="container">

        <div class="table-responsive text-nowrap">

            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Title</th>
                  <th scope="col">Price</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Total Price</th>
                </tr>
              </thead>
              <tbody>
                {% for order_item in cart.items.all %}
                <tr>
                  <th scope="row"></th>
                  <td>{{ order_item.item.title }}<br>
                      {% if order_item.lenses_required %}
                        {{order_item.lenses.power_type}} - {{order_item.lenses.lenses_type}}
                      {% else %}
                        Not Require Lenses? <a href = "{% url 'core:add_lenses' order_item.item.slug %}"><i class="fas fa-edit"></i></a>
                      {% endif %}
                  </td>
                  <td>₹{{ order_item.item.price }}</td>
                  <td>
                    <a  href = "{% url 'core:remove_single_item_from_cart' order_item.item.slug %}" class="ml-3"><i class="fas fa-minus"></i></a>
                      {{ order_item.quantity }}
                    <a href = "{% url 'core:add_to_cart' order_item.item.slug %}" class="mr-3"><i class="fas fa-plus"></i></a>
                  </td>
                  <td>
                    {% if order_item.get_total_discount_item_price %}
                      ₹{{ order_item.get_total_discount_item_price }}
                      <span class="badge badge-primary">Saving ₹{{ order_item.get_amount_saved }}</span>
                    {% else %}
                      ₹{{ order_item.get_total_item_price }}
                    {% endif %}
                    <a href="{% url 'core:remove_from_cart' order_item.item.slug %}" class="float-right text-danger"><i class="fas fa-trash"></i></a>
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="5" class="text-center"><b>Your Cart is Empty ¯\_(ツ)_/¯</b></td>
                </tr>
                {% endfor %}
                {% if cart.get_total_bill_amount %}
                <tr>
                  <td  colspan="4"><b>Total Cost</b></td>
                  <td><b>₹{{cart.get_total_bill_amount}}</b></td>
                </tr>

                {% endif %}
              </tbody>
            </table>

            <div class="float-right">
              <a class="btn btn-info" href="{% url 'core:home' %}">Back to shopping</a>
              <a  class="btn btn-primary" href="{% url 'core:checkout' %}">Proceed to checkout</a>
            </div>
        </div>

    </div>
  </main>
  <!--Main layout-->
{% endblock %}

templates/payment_cancelled.html
<h1>Payment Cancelled!</h1>

templates/paypal_payment.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
 
{% load cart_template_tags %}

{% load staticfiles %}

{% block head_title  %}Checkout{% endblock %}
{% block extra_head %}
<style>
  input[type="hidden"] {
    display: none;
    visibility: hidden;
    margin: 0px 0px 0px 0px;
  }
</style>
{% endblock extra_head %}
{% block content %}
  <!--Main layout-->
  <main >
    <div class="container wow fadeIn">

      <h2 class="my-5 h2 text-center">PayPal Payment</h2>

      <div class="row">

        <div class="col-md-12 mb-4">
        <!-- Heading -->
        <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Click to Pay</span>
        </h4>
          <div class="card">
            <div class="current-card-form">
              {{form.as_p}}
            </div>
          </div>
        </div>

        {% include "order_snippet.html" %}

      </div>

    </div>
  </main>
  <!--Main layout-->
{% endblock %}

templates/product_page.html
{% extends "base.html" %}

{% load staticfiles %}

{% block head_title  %}Product{% endblock %}

{% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-4 mb-4">
          <img src="{{ product.fview.url }}" class="mw-100" alt="{{product.slug}}">
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{product.get_category_display}}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            </div>

            <p class="lead">

              {% if product.discount_price %}
                <span class="mr-1">
                  <del>₹{{product.price}}</del>
                </span>
                <span>₹{{product.discount_price}}</span>
              {% else %}
                      {{product.price}}
              {% endif %}
              
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{product.features|safe}}</p>

            {%  comment %}<form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
            </form> {% endcomment %}
              <a class="btn btn-primary btn-md my-0 p" href="{{product.get_add_to_cart_url}}">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>
              
              <a class="btn btn-danger btn-md my-0 p" href="{{product.get_remove_from_cart_url}}">Remove from cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>{{product.description|safe}}</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4" style="margin: 0 auto;">

          <img src="{{product.sview.url}}" class="img-fluid" alt="{{product.title}}">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
{% endblock %}